server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  jpa:
    show-sql: true
  data:
    mongodb:
      uri: mongodb://abc:123456@localhost:27017/xc_cms
      authentication-database: xc_cms
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: debug




